#!/bin/bash

text=$(ruby bg2md -e -c -f -l -r "$1")

# section 1: fixes verses
#text=$(echo "$text" | sed -E '2{/^[^#]*$/d}')
#text=$(echo "$text" | sed -E 's/###### [0-9] /&  /g')
#text=$(echo "$text" | sed -E 's/###### [0-9][0-9] /& /g')
#text=$(echo "$text" | sed -E 's/###### [0-9][0-9][0-9] /&/g')
#text=$(echo "$text" | sed -E 's/^[^#]/    &/')
#text=$(echo "$text" | sed -E 's/###### //g')

# section 2: remove junk
#text=$(echo "$text" | sed -E 's/([!?.,”’:)])[A-Z][A-Za-z0-9: ].*/\1/g')
#text=$(echo "$text" | sed -E 's/##### Chapter [0-9]{1,3}//g')
#text=$(echo "$text" | sed -E 's/\*\*_//g')
#text=$(echo "$text" | sed -E 's/_\*\*//g')
#text=$(echo "$text" | sed -E 's/ ([!?.,”’:\)])/\1/g')
#text=$(echo "$text" | sed -E 's/ *$//g')
#text=$(echo "$text" | sed -E '/^$/d')

# section 3: make it fancy
#width=$(tput cols)
#text=$(echo "$text" | sed "s/^\(.\{$((width - 1))\}\)./&    /")
#text=$(echo "$text" | sed "s/^\(.\{$((width * 2 - 1))\}\)./&    /")
#text=$(echo "$text" | sed "s/^\(.\{$((width * 3 - 1))\}\)./&    /")
#text=$(echo "$text" | sed -E 's/([0-9]{1})    /\1   /g')
#text=$(echo "$text" | sed -E 's/([0-9]{2})   /\1  /g')
#text=$(echo "$text" | sed -E 's/([0-9]{3})  /\1 /g')

# section 4: verse lookup
#if [[ $2 != '' ]]; then
#  text=$(echo "$text" | sed -E ':a;$!{N;s/\n   //;ba;}')
#  echo "$text" | GREP_COLORS='ms=01;31' grep -E --color=always "^${2} .*" -A2 -B2 | less -RFX
#else
  echo "$text" #| less -FX
#fi
