#!/bin/bash

# FETCHING
text=$(ruby bg2md -e -c -f -l -r "$1")

# FORMATTING
## Delete the first heading
text=$(echo "$text" | sed -E '2{/^[^#]*$/d}')
## Format verses
text=$(echo "$text" | sed -E 's/###### [0-9] /&  /g')
text=$(echo "$text" | sed -E 's/###### [0-9][0-9] /& /g')
text=$(echo "$text" | sed -E 's/###### [0-9][0-9][0-9] /&/g')
## Add spacing to verses with newline
text=$(echo "$text" | sed -E 's/^[^#]/    &/')
## Remove verse headings
text=$(echo "$text" | sed -E 's/###### //g')
## Remove other headings
text=$(echo "$text" | sed -E 's/([!?.,”’:)])[A-Z][A-Za-z0-9: ].*/\1/g')
## Delete miscellaneous text
text=$(echo "$text" | sed -E 's/##### Chapter [0-9]{1,3}//g')
text=$(echo "$text" | sed -E 's/\*\*_//g')
text=$(echo "$text" | sed -E 's/_\*\*//g')
text=$(echo "$text" | sed -E 's/_//g')
## Fix spacing between punctuation marks
text=$(echo "$text" | sed -E 's/ ([!?.,”’:\)])/\1/g')
# Fit to terminal width
width=$(tput cols)
text=$(echo "$text" | sed "s/^\(.\{$((width - 1))\}\)./&    /")
text=$(echo "$text" | sed "s/^\(.\{$((width * 2 - 1))\}\)./&    /")
text=$(echo "$text" | sed "s/^\(.\{$((width * 3 - 1))\}\)./&    /")
text=$(echo "$text" | sed -E 's/([0-9]{1})    /\1   /g')
text=$(echo "$text" | sed -E 's/([0-9]{2})   /\1  /g')
text=$(echo "$text" | sed -E 's/([0-9]{3})  /\1 /g')
## Remove blank lines
text=$(echo "$text" | sed -E 's/ *$//g')
text=$(echo "$text" | sed -E '/^$/d')

# OUTPUT
## Locate verse
if [[ $2 != '' ]]; then
  text=$(echo "$text" | sed -E ':a;$!{N;s/\n   //;ba;}')
  echo "$text" | GREP_COLORS='ms=01;31' grep -E --color=always "^${2} .*" -A2 -B2 | less -RFX
else
  echo "$text" | less -FX
fi
